name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --verbose --release

      - name: Upload
        run: gh release upload ${{ github.event.release.tag_name }} target/release/testmate
        env:
          GH_TOKEN: ${{ github.token }}
